name: Spell Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/translations/*.json'
  push:
    branches:
      - main
    paths-ignore:
      - '**/translations/*.json'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@main
        with:
          config: cspell.json
